pipeline {
    agent {
        label 'docker'
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-mogli-creds') 
        DOCKER_REGISTRY = 'madaralmog'
        REPO_NAME = 'fe-exam'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        APP_PATH = 'exam-code/fe'
    }
    stages {
        stage('Clone Python Project') {
            steps {
                git branch: 'jenkins-workshop', url: 'https://github.com/almog2290/devopshift-welcome.git'
            }
        }

        stage('Lint & Security Scan'){
            parallel{
                stage('Lint'){
                    steps{
                        dir(env.APP_PATH){
                            sh '''
                                pip install flake8
                                flake8 . || true
                            '''
                        }
                    }
                }
                
                stage('Security Scan'){
                    steps{
                        dir(env.APP_PATH){
                            sh '''
                                pip install bandit
                                bandit -r . || true
                            '''
                        }
                    }
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir(env.APP_PATH){
                    sh '''
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir(env.APP_PATH){
                    sh "docker build -t $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG ."
                    sh "docker tag $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG $DOCKER_REGISTRY/$REPO_NAME:latest"
                }
            }
        }

        stage('Run Tests in Container') {
            steps {
                dir(env.APP_PATH){
                    sh "docker run --rm $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG pytest tests/"
                }
            }
        }

        stage('Integration Test with Docker Compose') {
            steps {
                dir('exam-code'){
                    sh 'docker compose up -d'
                    sleep time: 10, unit: 'SECONDS'  // Wait for services to start
                    sh 'curl -f http://localhost:5002 || exit 1'  // Adjust port for backend if needed
                    sh 'docker-compose down'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:latest"
            }
        }
    }
}
