pipeline {
    agent {
        label 'docker'
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-mogli-creds') 
        DOCKER_REGISTRY = 'madaralmog'
        REPO_NAME = 'frontend-workshop'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        APP_PATH = 'fe'
    }
    stages {
        stage('Clone Python Project') {
            steps {
                git branch: 'main', url: 'https://gitea.moglidev.xyz/mamba/jenkins_quiz_jb_frontend.git'
            }
        }

        stage('Lint & Security Scanning') {
            parallel{
                stage('Linting'){
                    stages{
                        stage('Lint python code'){
                            agent{
                                docker {
                                    image 'python:3.10'
                                    args '-v $HOME/.cache/pip:/root/.cache/pip'
                                    reuseNode true
                                }
                            }
                            steps{
                                dir(env.APP_PATH){
                                    echo "Linting python code(flake8)"
                                    sh '''
                                        python -m venv .venv
                                        . .venv/bin/activate  # source .venv/bin/activate (Bash)
                                        pip install flake8
                                        python -m flake8 ./src --exclude=tests
                                    '''
                                }
                            }
                        }
                        stage("Lint shell scripts"){
                            steps{
                                dir(env.APP_PATH){
                                    echo "Linting shell scripts"
                                    sh '''
                                        apt-get update
                                        apt install -y shellcheck
                                        FILES=$(find . -type f -name "*.sh")
                                        if [ -n "$FILES" ]; then
                                            echo "$FILES" | xargs shellcheck
                                        else
                                            echo "No shell scripts found"
                                        fi
                                    '''
                                }
                            }
                        }
                        stage("Lint Dockerfile"){
                            steps{
                                dir(env.APP_PATH){
                                    echo "Linting Dockerfile"
                                    sh '''
                                        ls -la
                                        docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock hadolint/hadolint < Dockerfile
                                    '''
                                }
                            }
                        }
                    }
                }
                stage("Security scan"){
                    stages{
                        stage('Security Scan - python code'){
                            agent{
                                docker {
                                    image 'python:3.10'
                                    args '-v $HOME/.cache/pip:/root/.cache/pip'
                                    reuseNode true
                                }
                            }
                            steps{
                                dir(env.APP_PATH){
                                    sh '''
                                        python -m venv .venv
                                        . .venv/bin/activate  # source .venv/bin/activate (Bash)
                                        pip install bandit
                                        python -m bandit -r ./src --exclude=tests
                                    '''
                                }
                            }
                        }
                        stage('Security Scan - Trivy'){
                            steps{
                                dir(env.APP_PATH){
                                    echo "Trivy , build temporary image for security scanning"
                                    sh '''
                                        docker build -t $DOCKER_REGISTRY/$REPO_NAME:trivy .
                                        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 0 --severity HIGH,CRITICAL $DOCKER_REGISTRY/$REPO_NAME:trivy
                                    '''
                                }
                            }
                        }
                    }
                }
            }
        }

        stage('Install Dependencies') {
            agent{
                docker {
                    image 'python:3.10'
                    args '-v $HOME/.cache/pip:/root/.cache/pip'
                    reuseNode true
                }
            }
            steps {
                dir(env.APP_PATH){
                    sh '''
                        export HOME=${WORKSPACE}
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir(env.APP_PATH){
                    sh "docker build -t $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG ."
                    sh "docker tag $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG $DOCKER_REGISTRY/$REPO_NAME:latest"
                }
            }
        }

        stage('Run Tests in Container') {
            steps {
                dir(env.APP_PATH){
                    sh "docker run --rm $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG pytest tests/"
                }
            }
        }

        stage('Integration Test with Docker Compose') {
            steps {
                sh '''
                    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    chmod +x /usr/local/bin/docker-compose
                '''
                sh 'docker-compose up -d'
                sleep time: 10, unit: 'SECONDS'  // Wait for services to start
                sh 'docker ps | grep -q 5002 && echo "Port 5002 is mapped and the container is running." || exit 1 ' // Adjust port for backend if needed
                sh 'docker-compose down'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:latest"
            }
        }
    }
    post {
        always {
            echo 'Cleaning up workspace'
            cleanWs()
        }
    }
}

